[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
external_signaling_address=${HOST_LAN_IP}
external_signaling_port=${SIP_PORT}
external_media_address=${HOST_LAN_IP}
${LOCAL_NET_LINES}
[transport-tcp]
type=transport
protocol=tcp
bind=0.0.0.0:5060
external_signaling_address=${HOST_LAN_IP}
external_signaling_port=${SIP_PORT}
external_media_address=${HOST_LAN_IP}
${LOCAL_NET_LINES}
[${SOFTPHONE_USERNAME}]
type=endpoint
context=from-softphone
disallow=all
allow=ulaw,alaw
auth=${SOFTPHONE_USERNAME}
aors=${SOFTPHONE_USERNAME}
direct_media=no
media_address=${HOST_LAN_IP}
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[${SOFTPHONE_USERNAME}]
type=auth
auth_type=userpass
username=${SOFTPHONE_USERNAME}
password=${SOFTPHONE_PASSWORD}

[${SOFTPHONE_USERNAME}]
type=aor
max_contacts=1
remove_existing=yes
qualify_frequency=30
